Query:
    type: object
    config:
        name: Query
        description: 'Root of the schema.'
        fields:
            viewer:
                resolve: "@=getUser()"
                type: 'User!'
                access: "@=hasRole('ROLE_USER')"
