User:
    type: object
    config:
        description: "A user is an individual's account."
        name: User
        fields:
            id:
                type: 'ID!'
                description: 'The ID of an object.'
            email:
                type: 'String!'
                description: 'The email address.'
